version: 0.1 
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    # IMPORTANT - Please verify your build commands
    build:
      commands: 
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*