version: 0.1
frontend:
   phases:
      build:
         commands:
            - npm build
    artifacts:
       baseDirectory: build
       files:
          - '**/*'
    cache:
       paths:
         - build/**/*

        